set(_CATKIN_CURRENT_PACKAGE "using_pointclouds")
set(using_pointclouds_VERSION "0.0.0")
set(using_pointclouds_MAINTAINER "mstest9 <mstest9@todo.todo>")
set(using_pointclouds_PACKAGE_FORMAT "1")
set(using_pointclouds_BUILD_DEPENDS "pcl_msgs" "roscpp")
set(using_pointclouds_BUILD_EXPORT_DEPENDS "pcl_msgs" "roscpp")
set(using_pointclouds_BUILDTOOL_DEPENDS "catkin")
set(using_pointclouds_BUILDTOOL_EXPORT_DEPENDS )
set(using_pointclouds_EXEC_DEPENDS "pcl_msgs" "roscpp")
set(using_pointclouds_RUN_DEPENDS "pcl_msgs" "roscpp")
set(using_pointclouds_TEST_DEPENDS )
set(using_pointclouds_DOC_DEPENDS )
set(using_pointclouds_DEPRECATED "")